name: Deploy Azure Functions with Terraform

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the main branch

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0  # Use the appropriate Terraform version

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup DotNet Environment
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: '8.x'
          
    # Restore dependencies for the solution
    - name: Restore dependencies
      run: dotnet restore
      
    # Build the solution 
    - name: Build the solution
      run: dotnet build --configuration Release --no-restore

    # Publish the function apps
    - name: Deploy Sender Function
      uses: Azure/functions-action@v1
      id: sender
      with:
        app-name: "sender-function-app"
        slot-name: 'Production'
        package: "./Sender/bin/Release/net8.0"  # Path to your sender function app publish directory

    - name: Deploy Receiver Function
      uses: Azure/functions-action@v1
      id: receiver
      with:
        app-name: "receiver-function-app"
        slot-name: 'Production'
        package: "./Receiver/bin/Release/net8.0"  # Path to your receiver function app publish directory
